#!/bin/bash
set -euo pipefail
OUT_DIR="$HOME/MT5-MSZZ-TEST/StageA_Configs"
RR_VALUES=(1.0 1.5 2.0 3.0)
MAGIC_BASE=26072700

count=0
for rr in "${RR_VALUES[@]}"; do
   count=$((count+1))
   rr_label=$(echo "$rr" | tr -d '.')
   report_name="StageA_research_FastBreakout_RR${rr_label}"
   out_file="${OUT_DIR}/stageA_research_FastBreakout_RR${rr_label}.ini"
   magic=$((MAGIC_BASE + count))

   {
      echo ";D019 research eligibility: FastBreakout only, InpResearchMinScoreOverride=3.5, RiskReward=${rr}"
      echo "[Tester]"
      echo "Expert=MultiSpeedZigZagEA"
      echo "Symbol=XAUUSD"
      echo "Period=M5"
      echo "Optimization=0"
      echo "Model=2"
      echo "FromDate=2025.03.01"
      echo "ToDate=2026.07.24"
      echo "ForwardMode=0"
      echo "Deposit=10000"
      echo "Currency=USD"
      echo "Leverage=500"
      echo "ExecutionMode=0"
      echo "OptimizationCriterion=0"
      echo "Visual=0"
      echo "ShutdownTerminal=1"
      echo "Report=${report_name}"
      echo "ReplaceReport=1"
      echo "[TesterInputs]"
      echo "InpShadowOnly=false||false||0||true||N"
      echo "InpAllowLiveExecution=true||false||0||true||N"
      echo "InpAcknowledgeRisk=true||false||0||true||N"
      echo "InpMagic=${magic}||0||0||0||N"
      echo "InpHistoryBars=1500||300||0||3000||N"
      echo "InpFastATRLen=14||0||0||0||N"
      echo "InpFastATRMult=1.0||0||0||0||N"
      echo "InpMedATRLen=14||0||0||0||N"
      echo "InpMedATRMult=2.0||0||0||0||N"
      echo "InpSlowATRLen=14||0||0||0||N"
      echo "InpSlowATRMult=3.5||0||0||0||N"
      echo "InpEnableFastBreakout=true||false||0||true||N"
      echo "InpEnableMediumBreakout=false||false||0||true||N"
      echo "InpEnableSlowBreakout=false||false||0||true||N"
      echo "InpEnableFastMedConfluence=false||false||0||true||N"
      echo "InpEnableFastMedContext=false||false||0||true||N"
      echo "InpEnableMedSlowContext=false||false||0||true||N"
      echo "InpEnableNestedPullback=false||false||0||true||N"
      echo "InpEnableWeightedEnsemble=false||false||0||true||N"
      echo "InpMinBarsBetween=3||0||0||0||N"
      echo "InpMinScore=5.0||0||0||0||N"
      echo "InpResearchMinScoreOverride=3.5||0||0||0||N"
      echo "InpAcknowledgeResearchOverride=true||false||0||true||N"
      echo "InpRiskReward=${rr}||0||0||0||N"
      echo "InpOneOwnedPositionPerSymbol=true||false||0||true||N"
      echo "InpSignalValidityBars=3||0||0||0||N"
      echo "InpFixedLots=0.01||0||0||0||N"
      echo "InpMaxSpreadPoints=80.0||0||0||0||N"
      echo "InpDeviationPoints=30||0||0||0||N"
      echo "InpExitOwnedOpposite=true||false||0||true||N"
      echo "InpMaxPersistentEvents=2000||0||0||0||N"
      echo "InpMarginBufferRatio=1.0||0||0||0||N"
      echo "InpKillSwitchEngaged=false||false||0||true||N"
      echo "InpMaxTradesPerDay=1000||0||0||0||N"
      echo "InpMaxDailyLossAmount=0.0||0||0||0||N"
      echo "InpWriteCSV=true||false||0||true||N"
      echo "InpVerboseLog=true||false||0||true||N"
   } > "$out_file"
   echo "wrote $out_file"
done
